[toolchain]
channel = "1.88.0"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-docs",
	"rust-src",
	"rust-std",
	"rustc",
	"rustfmt",
]
targets = ["wasm32-unknown-unknown", "wasm32v1-none"]
profile = "minimal"
